version: "3"
services:
  webapi:
    image: apifood
    container_name: apifood
    build:
      args:
        buildconfig: Debug
      context: ../APINET
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5003
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27018"